# Generated by Django 4.2.16 on 2026-06-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usage_tracking", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiusage",
            new_name="usage_track_api_nam_1a2812_idx",
            old_name="usage_track_api_nam_hour_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="llmcalllog",
            new_name="usage_track_request_84f6dd_idx",
            old_name="usage_track_request_id_idx",
        ),
        migrations.RenameIndex(
            model_name="llmcalllog",
            new_name="usage_track_user_id_aace0b_idx",
            old_name="usage_track_user_created_idx",
        ),
    ]
